#
# /etc/initconf.py - Init configuration file
# Generated by gConfig-Init
# Copyright 2004, Forty-two

TIMEZONE = "/usr/share/zoneinfo/US/Eastern"
KEYMAP = "/usr/share/kbd/keymaps/i386/dvorak/dvorak.map.gz"
FONT = ""
MODULES = [ "ide-scsi", "sundance", "i810_audio" ]
BACKUP = "yes"
BACKUPS = [ "/etc/fstab", "/etc/initconf.py" ]
PARALLEL = "yes"
DAEMONS = [  ]
HOSTNAME = ""
INTERFACES = { "lo":"lo 127.0.0.1" }