#
# /etc/initconf.py - Init configuration file
# Generated by gConfig-Init
# Copyright 2004, Forty-two

TIMEZONE = ""
KEYMAP = ""
FONT = ""
MODULES = [  ]
BACKUP = "yes"
BACKUPS = [  ]
PARALLEL = "yes"
DAEMONS = [  ]
HOSTNAME = ""
INTERFACES = { "lo":"lo 127.0.0.1" }