#!/usr/bin/env python
#
# example of pyGTK with tables
#

import pygtk
pygtk.require( "2.0" )
import gtk

class MainWindow:
	def delete_event( self, widget, event, data=None ):
		gtk.main_quit()
		return gtk.FALSE

	def forward_clicked( self, widget, data=None ):
		print "I would be going forward..."

	def __init__( self ):
		self.window1 = gtk.Window( gtk.WINDOW_TOPLEVEL )
		self.window1.set_title( "Init Configuration" )
		self.window1.connect( "delete_event", self.delete_event )
		self.window1.set_border_width( 20 )
		main_table = gtk.Table( 2, 2, gtk.FALSE )
		self.window1.add( main_table )
		label = gtk.Label( "Welcome to the Init Configuration program. You will now be prompted a series of questions about your computer which we will then use to generate a /etc/initconf.py file - the configuration file for the init scripts. For more information, see http://forty-two.berlios.de. Click 'Forward' to continue." )
		label.set_line_wrap( gtk.TRUE )
		main_table.attach( label, 0, 2, 0, 1 )
		main_table.set_row_spacings( 5 )
		main_table.set_col_spacings( 10 )
		label.show()
		forward_button = gtk.Button( "Forward", gtk.STOCK_GO_FORWARD )
		forward_button.connect( "clicked", self.forward_clicked, "Forward" )
		main_table.attach( forward_button, 1, 2, 1, 2 )
		forward_button.show()
		quit_button = gtk.Button( "Quit", gtk.STOCK_QUIT )
		quit_button.connect( "clicked", lambda w: gtk.main_quit() )
		main_table.attach( quit_button, 0, 1, 1, 2 )
		quit_button.show()
		main_table.show()
		self.window1.show()

def main():
	gtk.main()
	return 0

if __name__ == "__main__":
	MainWindow()
	main()
