#!/usr/bin/env python
#
# example of pyGTK with tables
#

import pygtk
pygtk.require( "2.0" )
import gtk

class MainWindow:
	def delete_event( self, widget, event, data=None ):
		gtk.main_quit()
		return gtk.FALSE

	def forward_clicked( self, widget, data=None ):
		print "I would be going forward..."

	def __init__( self ):
		self.window1 = gtk.Window( gtk.WINDOW_TOPLEVEL )
		self.window1.set_title( "Init Configuration" )
		self.window1.connect( "delete_event", self.delete_event )
		self.window1.set_border_width( 20 )
		main_box = gtk.VBox( gtk.FALSE, 2 )
		self.window1.add( main_box )
		label = gtk.Label( "Welcome to the Init Configuration program. You will now be prompted a series of questions about your computer which we will then use to generate a /etc/initconf.py file - the configuration file for the init scripts. For more information, see http://forty-two.berlios.de. Click 'Forward' to continue." )
		label.set_line_wrap( gtk.TRUE )
		main_box.pack_start( label, gtk.FALSE, gtk.FALSE, 2 )
		label.show()
		forward_button = gtk.Button( "Forward", gtk.STOCK_GO_FORWARD )
		forward_button.connect( "clicked", self.forward_clicked, "Forward" )
		main_box.pack_start( forward_button, gtk.FALSE, gtk.FALSE, 2 )
		forward_button.show()
		main_box.show()
		self.window1.show()

def main():
	gtk.main()
	return 0

if __name__ == "__main__":
	MainWindow()
	main()
