#!/usr/bin/python
#
# GTK+ >= 2.0 configuration utility for Forty-two (init scripts)
#
# Editors: undeadpenguin


# Import everything
import pygtk
pygtk.require( "2.0" )
import gtk

# Define global variables
TIMEZONE = ""
FONT = ""
KEYMAP = ""
MODULES = [ "" ]
BACKUP = ""
BACKUPS = [ "" ]
DAEMONS = [ "" ]
HOSTNAME = [ "" ]
INTERFACES = { "":"" }

class MainWindow:
	
	# Called when window is closed
	def delete_event( self, widget, event, data=None ):
		gtk.main_quit()
		return gtk.FALSE

	def __init__( self ):

		# Start the window
		self.window1 = gtk.Window( gtk.WINDOW_TOPLEVEL )
		self.window1.set_title( "gConfig-Init" )
		self.window1.connect( "delete_event", self.delete_event )
		self.window1.set_border_width( 20 )

		# Create the main VBox
		self.main_vbox = gtk.VBox( gtk.FALSE, 10 )
		self.window1.add( self.main_vbox )

		# Create HBox 1 (to hold the buttons)
		self.hbox1 = gtk.HBox( gtk.FALSE, 20 )

		# Create buttons for the HBox
		self.cancel_button = gtk.Button( "Cancel", gtk.STOCK_CANCEL )
		self.cancel_button.connect( "clicked", self.delete_event, "destroy" )
		self.forward_button = gtk.Button( "Forward", gtk.STOCK_GO_FORWARD )

		# Add them to the HBox
		self.hbox1.pack_start( self.cancel_button, gtk.TRUE, gtk.TRUE, 20 )
		self.hbox1.pack_end( self.forward_button, gtk.TRUE, gtk.TRUE, 20 )
		
		# Create the separator
		self.hseparator1 = gtk.HSeparator()

		# Create the label
		self.label1 = gtk.Label( "Welcome to gConfig-Init. This program will help you to configure your init scripts, telling your computer what services to load at boot. No changes will be made to your system until you've entered everything. You may hit 'Cancel' any time to quit the program." )
		self.label1.set_line_wrap( gtk.TRUE )

		# Create the image
		self.gconfig_image = gtk.Image()
		self.gconfig_image.set_from_file( "imgs/gconfig-init.png" )


		# Add everything to the VBox
		self.main_vbox.pack_start( self.gconfig_image, gtk.TRUE, gtk.TRUE, 10 )
		self.main_vbox.pack_start( self.label1, gtk.TRUE, gtk.TRUE, 10 )
		self.main_vbox.pack_start( self.hseparator1, gtk.TRUE, gtk.TRUE, 10 )
		self.main_vbox.pack_start( self.hbox1, gtk.TRUE, gtk.TRUE, 10 )

		# Show everything
		self.cancel_button.show()
		self.forward_button.show()
		self.hbox1.show()
		self.hseparator1.show()
		self.label1.show()
		self.gconfig_image.show()
		self.main_vbox.show()
		self.window1.show()



def main():
	gtk.main()
	return 0

if __name__ == "__main__":
	MainWindow()
	main()
